languageCode = "es-ar"
title = "Carlos Martín"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "It's just a blog."
  copyright = "© Carlos Martín - all articles under Creative Commons CC-BY license"
  dark = "auto"
  highlight = true
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "log"
    name = "log"
    title = "log"
    url = "/log/"
    weight = 3

[permalinks]
  posts = "/:title/"
  log = "/log/:filename/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
