languageCode = "es-ar"
title = "Carlos Mart√≠n Blog"
theme = "etch"

[[menu.main]]
name = "about"
identifier = "about"
weight = 200
url = "/about/"


[[menu.main]]
name = "posts"
identifier = "posts"
weight = 200
url = "/posts"

